server:
  port: 8767

spring:
  application:
    name: order

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

#开启熔断器开关
feign:
  hystrix:
    enabled: true