server:
  port: 8767

spring:
  application:
    name: order
  boot:
    admin:
      client:
        url: http://localhost:8771

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

#开启熔断器开关
feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"